60 update exportinputdialog component
trelliscope/trelliscopejs-lib pull request #106
Opened 2022-09-08 17:40 UTC by dpenciso

2022-09-08 18:40 UTC, Incin requested changes

2022-09-08 18:40 UTC, Incin commented on src/components/ExportInputDialog/ExportInputDialog.tsx
> +//       aria-labelledby={`full-width-tab-${index}`}
can this commented out code just be removed?

2022-09-08 18:40 UTC, Incin commented on src/components/ExportInputDialog/ExportInputDialog.tsx
> +  [key: string]: any;
we should be able to figure out what this type is, i dont think we want an any here

2022-09-08 18:40 UTC, Incin commented on src/index.js
> +trelliscopeApp('62e90658', '_test/gapminder_bells/config.jsonp', { logger: true });
i think we decided to not commit these changes. So lets leave it as the standard config.jsonp

2022-09-08 18:51 UTC, dpenciso commented on src/components/ExportInputDialog/ExportInputDialog.tsx
> +//       aria-labelledby={`full-width-tab-${index}`}
jeff said to leave it commented

2022-09-08 18:51 UTC, dpenciso commented on src/components/ExportInputDialog/ExportInputDialog.tsx
> +  [key: string]: any;
walked through it with jeff. he said to do this

2022-09-08 18:52 UTC, dpenciso commented on src/index.js
> +trelliscopeApp('62e90658', '_test/gapminder_bells/config.jsonp', { logger: true });
good call

2022-09-09 16:05 UTC, Incin approved these changes

2022-09-09 16:05 UTC, merged