Convert ui reducer to slice
trelliscope/trelliscopejs-lib pull request #278
Opened 2022-10-28 21:43 UTC by jefferymills

2022-10-31 14:43 UTC, dpenciso requested changes

2022-10-31 14:43 UTC, dpenciso commented on src/index.tsx
> +trelliscopeApp('96c61ca5', '_test/trelliscope-examples2/gapminder_reldisp/config.jsonp', { logger: true });
did we want this changed?

2022-11-01 15:26 UTC, Incin commented on public/mockServiceWorker.js
> + * Mock Service Worker (0.47.4).
did we want this version incremented?

2022-11-01 15:26 UTC, Incin approved these changes

2022-11-01 19:57 UTC, jefferymills commented on public/mockServiceWorker.js
> + * Mock Service Worker (0.47.4).
This just happened from running `yarn install` and it's a patch update so we probably do want it.

2022-11-01 19:57 UTC, jefferymills commented on src/index.tsx
> +trelliscopeApp('96c61ca5', '_test/trelliscope-examples2/gapminder_reldisp/config.jsonp', { logger: true });
No, I'll fix that.

2022-11-01 22:00 UTC, Incin approved these changes

2022-11-01 22:45 UTC, Incin approved these changes

2022-11-02 21:58 UTC, Incin approved these changes

2022-11-03 21:41 UTC, merged