545 add support to iframes to panel component 1
trelliscope/trelliscopejs-lib pull request #597
Opened 2023-02-03 22:50 UTC by jefferymills

2023-02-03 23:05 UTC, Incin requested changes

2023-02-03 23:05 UTC, Incin commented on public/index.html
> +  <!--  <div id="1060b383" class="trelliscope-spa"></div> -->
did we want to commit this?

2023-02-03 23:05 UTC, Incin commented on src/components/ContentNew/ContentNew.tsx
> +  console.log(displayInfo);
console log

2023-02-03 23:05 UTC, Incin commented on src/index.tsx
> +// trelliscopeApp('960f51e6', '_test/trelliscope-examples3/gapminder_bells/config.jsonp', { logger: true });
did you want to commit this?

2023-02-06 18:32 UTC, jefferymills commented on src/index.tsx
> +// trelliscopeApp('960f51e6', '_test/trelliscope-examples3/gapminder_bells/config.jsonp', { logger: true });
Personally it feels like when we're working on a feature branch it's simpler to just not worry about these lines. I think maybe we just worry about it on develop and master. @Incin @dpenciso Thoughts?

2023-02-06 19:59 UTC, jefferymills commented on src/index.tsx
> +// trelliscopeApp('960f51e6', '_test/trelliscope-examples3/gapminder_bells/config.jsonp', { logger: true });
Updated anyways so I can merge.

2023-02-06 19:59 UTC, merged